export type PlaybookEntry = {
  id: string;
  content: string;
  source?: string;
};

export type PlaybookData = {
  quotes: PlaybookEntry[];
  advice: PlaybookEntry[];
  tips: PlaybookEntry[];
};

export const playbookData: PlaybookData = {
  quotes: [
    { id: 'q1', content: "A successful marriage requires falling in love many times, always with the same person.", source: "Mignon McLaughlin" },
    { id: 'q2', content: "To love and be loved is to feel the sun from both sides.", source: "David Viscott" },
    { id: 'q3', content: "Where there is love there is life.", source: "Mahatma Gandhi" },
    { id: 'q4', content: "Grow old along with me! The best is yet to be.", source: "Robert Browning" },
    { id: 'q5', content: "A great marriage is not when the 'perfect couple' comes together. It is when an imperfect couple learns to enjoy their differences.", source: "Dave Meurer" },
    { id: 'q6', content: "The best thing to hold onto in life is each other.", source: "Audrey Hepburn" },
    { id: 'q7', content: "We love because it's the only true adventure.", source: "Nikki Giovanni" },
    { id: 'q8', content: "Love is composed of a single soul inhabiting two bodies.", source: "Aristotle" },
    { id: 'q9', content: "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.", source: "Lao Tzu" },
    { id: 'q10', content: "True love stories never have endings.", source: "Richard Bach" },
    { id: 'q11', content: "Love doesn't make the world go 'round. Love is what makes the ride worthwhile.", source: "Franklin P. Jones" },
    { id: 'q12', content: "Keep love in your heart. A life without it is like a sunless garden when the flowers are dead.", source: "Oscar Wilde" },
    { id: 'q13', content: "The greatest happiness of life is the conviction that we are loved.", source: "Victor Hugo" },
    { id: 'q14', content: "Love is the master key that opens the gates of happiness.", source: "Oliver Wendell Holmes" },
    { id: 'q15', content: "In all the world, there is no heart for me like yours. In all the world, there is no love for you like mine.", source: "Maya Angelou" },
    { id: 'q16', content: "Whatever our souls are made of, his and mine are the same.", source: "Emily Brontë" },
    { id: 'q17', content: "If I know what love is, it is because of you.", source: "Hermann Hesse" },
    { id: 'q18', content: "You know you're in love when you can't fall asleep because reality is finally better than your dreams.", source: "Dr. Seuss" },
    { id: 'q19', content: "The first duty of love is to listen.", source: "Paul Tillich" },
    { id: 'q20', content: "Love isn't something you find. Love is something that finds you.", source: "Loretta Young" },
    { id: 'q21', content: "Two souls with but a single thought; two hearts that beat as one.", source: "John Keats" },
    { id: 'q22', content: "Love is a friendship set to music.", source: "Joseph Campbell" },
    { id: 'q23', content: "You are my heart, my life, my one and only thought.", source: "Arthur Conan Doyle" },
    { id: 'q24', content: "My love for you is a journey; starting at forever, and ending at never.", source: "Anonymous" },
    { id: 'q25', content: "Love is the enchanted dawn of every virtue.", source: "Ralph Waldo Emerson" },
    { id: 'q26', content: "To find someone who will love you for no reason, and to shower that person with reasons, that is the ultimate happiness.", source: "Robert Brault" },
    { id: 'q27', content: "There is no remedy for love but to love more.", source: "Henry David Thoreau" },
    { id: 'q28', content: "If I had a flower for every time I thought of you... I could walk through my garden forever.", source: "Alfred Tennyson" },
    { id: 'q29', content: "Loving you never was an option. It was a necessity.", source: "Truth Devour" },
    { id: 'q30', content: "One word frees us of all the weight and pain of life: that word is love.", source: "Sophocles" },
    { id: 'q31', content: "The heart wants what it wants. There's no logic to these things. You meet someone and you fall in love and that's that.", source: "Woody Allen" },
    { id: 'q32', content: "Love is that condition in which the happiness of another person is essential to your own.", source: "Robert A. Heinlein" },
    { id: 'q33', content: "Life without love is like a tree without blossoms or fruit.", source: "Khalil Gibran" },
    { id: 'q34', content: "Gravity is not responsible for people falling in love.", source: "Albert Einstein" },
    { id: 'q35', content: "Love is like a beautiful flower which I may not touch, but whose fragrance makes the garden a place of delight just the same.", source: "Helen Keller" },
    { id: 'q36', content: "A soul mate is not someone who comes into your life and is perfect. It's someone who comes in and makes you want to be better.", source: "Anonymous" },
    { id: 'q37', content: "Love is the extremely difficult realization that something other than oneself is real.", source: "Iris Murdoch" },
    { id: 'q38', content: "The heart has its reasons of which reason knows nothing.", source: "Blaise Pascal" },
    { id: 'q39', content: "There is only one happiness in this life, to love and be loved.", source: "George Sand" },
    { id: 'q40', content: "I love you not only for what you are, but for what I am when I am with you.", source: "Elizabeth Barrett Browning" },
    { id: 'q41', content: "Marriages are like fingerprints; each one is different and each one is beautiful.", source: "Maggie Reyes" },
    { id: 'q42', content: "A wedding is a funeral where you smell your own flowers.", source: "Eddie Cantor" }, // Adding some personality
    { id: 'q43', content: "Marriage is the highest state of friendship. If happy, it lessens our cares by dividing them, at the same time that it doubles our pleasures by mutual participation.", source: "Samuel Richardson" },
    { id: 'q44', content: "A happy marriage is a long conversation which always seems too short.", source: "Andre Maurois" },
    { id: 'q45', content: "Love is a many-splendored thing. Love lifts us up where we belong.", source: "Moulin Rouge" },
    { id: 'q46', content: "I would rather share one lifetime with you than face all the ages of this world alone.", source: "J.R.R. Tolkien" },
    { id: 'q47', content: "You are the finest, loveliest, tenderest, and most beautiful person I have ever known—and even that is an understatement.", source: "F. Scott Fitzgerald" },
    { id: 'q48', content: "Love is something eternal; the aspect may change, but not the essence.", source: "Vincent van Gogh" },
    { id: 'q49', content: "A lover is a man who tries to be more amiable than it is possible for him to be. This is why almost all lovers are ridiculous.", source: "Nicolas Chamfort" },
    { id: 'q50', content: "Love is an act of endless forgiveness, a tender look which becomes a habit.", source: "Peter Ustinov" },
    { id: 'q51', content: "Chains do not hold a marriage together. It is threads, hundreds of tiny threads, which sew people together through the years.", source: "Simone Signoret" },
    { id: 'q52', content: "When you realize you want to spend the rest of your life with somebody, you want the rest of your life to start as soon as possible.", source: "When Harry Met Sally" },
    { id: 'q53', content: "The real act of marriage takes place in the heart, not in the ballroom or church or synagogue.", source: "Barbara De Angelis" },
    { id: 'q54', content: "Marriage is not about age; it's about finding the right person.", source: "Sophia Bush" },
    { id: 'q55', content: "The secret of a happy marriage is finding the right person. You know they're right if you love to be with them all the time.", source: "Julia Child" },
    { id: 'q56', content: "Being in love is the only transcendent state that is truly accessible to everyone.", source: "Rainer Maria Rilke" },
    { id: 'q57', content: "To be fully seen by somebody, then, and be loved anyhow - this is a human offering that can border on miraculous.", source: "Elizabeth Gilbert" },
    { id: 'q58', content: "True love is rare, and it's the only thing that gives life real meaning.", source: "Nicholas Sparks" },
    { id: 'q59', content: "Love means to commit oneself without guarantee.", source: "Erich Fromm" },
    { id: 'q60', content: "We were together. I forget the rest.", source: "Walt Whitman" },
    { id: 'q61', content: "Thinking of you keeps me awake. Dreaming of you keeps me asleep. Being with you keeps me alive.", source: "Unknown" },
    { id: 'q62', content: "My heart is and always will be yours.", source: "Jane Austen" },
    { id: 'q63', content: "Love asks me no questions, and gives me endless support.", source: "William Shakespeare" },
    { id: 'q64', content: "I loved her against reason, against promise, against peace, against hope, against happiness, against all discouragement that could be.", source: "Charles Dickens" },
    { id: 'q65', content: "The beauty of marriage is that, if you chose the right person and you both love each other, you always have a friend shift through the weeds of life with you.", source: "Unknown" },
    { id: 'q66', content: "Marriage: a legal or religious ceremony by which two persons of the opposite sex solemnly agree to harass and impede each other for twenty-five years.", source: "Ambrose Bierce" },
    { id: 'q67', content: "To get the full value of joy you must have someone to divide it with.", source: "Mark Twain" },
    { id: 'q68', content: "Love is like the wind, you can't see it but you can feel it.", source: "Nicholas Sparks" },
    { id: 'q69', content: "Each time you love, love as deeply as if it were forever.", source: "Audre Lorde" },
    { id: 'q70', content: "Love has nothing to do with what you are expecting to get only with what you are expecting to give — which is everything.", source: "Katharine Hepburn" },
    { id: 'q71', content: "Love is a choice you make every day.", source: "Gary Chapman" },
    { id: 'q72', content: "Whatever our souls are made of, his and mine are the same.", source: "Emily Brontë" },
    { id: 'q73', content: "A successful marriage requires falling in love many times, always with the same person.", source: "Mignon McLaughlin" },
    { id: 'q74', content: "Love is an untamed force. When we try to control it, it destroys us. When we try to imprison it, it enslaves us. When we try to understand it, it leaves us feeling lost and confused.", source: "Paulo Coelho" },
    { id: 'q75', content: "Love is a gift of one's innermost self to another so that both may be whole.", source: "Buddha" },
    { id: 'q76', content: "There is only one happiness in this life, to love and be loved.", source: "George Sand" },
    { id: 'q77', content: "Love is the master key that opens the gates of happiness.", source: "Oliver Wendell Holmes" },
    { id: 'q78', content: "I can't imagine my life without you.", source: "Unknown" },
    { id: 'q79', content: "You are the one I've been waiting for my whole life.", source: "Unknown" },
    { id: 'q80', content: "A man's best friend is his wife.", source: "Unknown" },
    { id: 'q81', content: "In all the world, there is no heart for me like yours.", source: "Maya Angelou" },
    { id: 'q82', content: "Marriage is the process by which two people who are already related become related.", source: "Unknown" },
    { id: 'q83', content: "To find someone who will love you for no reason, and to shower that person with reasons, that is the ultimate happiness.", source: "Robert Brault" },
    { id: 'q84', content: "Love is a game that two can play and both win.", source: "Eva Gabor" },
    { id: 'q85', content: "Marriage is not a noun; it's a verb. It isn't something you get. It's something you do.", source: "Barbara De Angelis" },
    { id: 'q86', content: "The best thing to hold onto in life is each other.", source: "Audrey Hepburn" },
    { id: 'q87', content: "Love makes your soul crawl out from its hiding place.", source: "Zora Neale Hurston" },
    { id: 'q88', content: "You don't marry someone you can live with—you marry someone you cannot live without.", source: "Unknown" },
    { id: 'q89', content: "At the touch of love everyone becomes a poet.", source: "Plato" },
    { id: 'q90', content: "Love recognizes no barriers. It jumps hurdles, leaps fences, penetrates walls to arrive at its destination full of hope.", source: "Maya Angelou" },
    { id: 'q91', content: "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.", source: "Lao Tzu" },
    { id: 'q92', content: "We are most alive when we're in love.", source: "John Updike" },
    { id: 'q93', content: "Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.", source: "Rumi" },
    { id: 'q94', content: "To love is to recognize yourself in another.", source: "Eckhart Tolle" },
    { id: 'q95', content: "Love is the only gold.", source: "Alfred Tennyson" },
    { id: 'q96', content: "Love comforteth like sunshine after rain.", source: "William Shakespeare" },
    { id: 'q97', content: "Life is the flower for which love is the honey.", source: "Victor Hugo" },
    { id: 'q98', content: "The greatest thing you'll ever learn is just to love and be loved in return.", source: "Eden Ahbez" },
    { id: 'q99', content: "Love is the crowning grace of humanity, the holyest right of the soul, the golden link which binds us to duty and truth, the redeeming spell that out of the life of the people shapes the form of a new heaven and a new earth.", source: "Petrarch" },
    { id: 'q100', content: "A hundred hearts would be too few to carry all my love for you.", source: "Unknown" }
  ],
  advice: [
    { id: 'a1', content: "Never go to bed angry. Stay up and fight.", source: "Phyllis Diller" },
    { id: 'a2', content: "Communication is the lifeline of any relationship. When you stop communicating, you stop relating." },
    { id: 'a3', content: "Always be each other's biggest fan and loudest cheerleader." },
    { id: 'a4', content: "The secret to a long marriage is to stay in love, stay together, and never stop dating each other." },
    { id: 'a5', content: "Learn to apologize when you are wrong, and learn to forgive when you are right." },
    { id: 'a6', content: "Marriage is not a 50/50 split; it's 100/100. You both give your all every single day." },
    { id: 'a7', content: "Keep your sense of humor. Laughter is the glue that holds everything together." },
    { id: 'a8', content: "Listen more than you speak. Sometimes your partner just needs to be heard." },
    { id: 'a9', content: "Don't sweat the small stuff. Most of what you argue about won't matter in 5 years." },
    { id: 'a10', content: "Prioritize your relationship. Your children, parents, and friends are important, but your spouse comes first." },
    { id: 'a11', content: "Celebrate the small wins together. Every milestone in your marriage is worth a toast." },
    { id: 'a12', content: "Never stop learning about your partner. People grow and change, and discovering your spouse's new interests is a joy." },
    { id: 'a13', content: "Practice radical honesty. Trust is the foundation of everything else." },
    { id: 'a14', content: "Be kind. Even when you're tired, stressed, or frustrated, kindness should be your default mode." },
    { id: 'a15', content: "Show your appreciation daily. A simple 'thank you for doing the dishes' goes a long way." },
    { id: 'a16', content: "Don't compare your marriage to others. You only see the highlight reel of other people's lives." },
    { id: 'a17', content: "Build a life of your own too. Having individual hobbies and friends makes you a more interesting partner." },
    { id: 'a18', content: "Respect your partner's boundaries. Understanding each other's needs for space and privacy is healthy." },
    { id: 'a19', content: "Keep the romance alive. Surprise each other with little gifts or notes often." },
    { id: 'a20', content: "Be a team. In every decision, remember that it's the two of you against the problem, not against each other." },
    { id: 'a21', content: "Validate your partner's feelings. Even if you don't agree, acknowledge that their emotions are real." },
    { id: 'a22', content: "Set goals together. Whether it's travel, financial, or personal, having a shared vision is powerful." },
    { id: 'a23', content: "Limit your screen time. Be present with each other without the distraction of phones." },
    { id: 'a24', content: "Don't let outside influences dictate your relationship. Listen to advice, but ultimately do what's best for you both." },
    { id: 'a25', content: "Apologize quickly and fully. No 'I'm sorry, but...' statements." },
    { id: 'a26', content: "Forgive quickly and completely. Don't keep a tally of past mistakes." },
    { id: 'a27', content: "Make time for physical intimacy. It's a vital part of staying connected." },
    { id: 'a28', content: "Support each other's dreams. Even if they seem out of reach, be the one who believes in them." },
    { id: 'a29', content: "Handle finances together. Be transparent about money and make a plan that works for both." },
    { id: 'a30', content: "Talk about your expectations. Many conflicts arise from unspoken assumptions." },
    { id: 'a31', content: "Keep your fights private. Don't air your grievances to friends or family." },
    { id: 'a32', content: "Spend time with other healthy couples. Their positive energy can be contagious." },
    { id: 'a33', content: "Learn each other's love languages. It helps you express love in a way your partner truly feels it." },
    { id: 'a34', content: "Be patient with each other. Growth takes time, and we all have bad days." },
    { id: 'a35', content: "Don't try to change your partner. Love them for who they are, not who you want them to be." },
    { id: 'a36', content: "A marriage is like a garden. It needs constant care and attention to thrive." },
    { id: 'a37', content: "Be willing to compromise. It's about finding a middle ground that makes you both happy." },
    { id: 'a38', content: "Keep your promises. Integrity is everything in a relationship." },
    { id: 'a39', content: "Express your needs clearly. Don't expect your partner to read your mind." },
    { id: 'a40', content: "Don't bring up the past during an argument. Focus on the current issue at hand." },
    { id: 'a41', content: "Nurture your friendship. At the core, you should be each other's best friend." },
    { id: 'a42', content: "Take care of yourself. You can't be a good partner if you're not in a good place yourself." },
    { id: 'a43', content: "Be open about your fears and vulnerabilities. It builds deep intimacy." },
    { id: 'a44', content: "Create your own traditions. They give your marriage a unique identity." },
    { id: 'a45', content: "Admit your mistakes. Vulnerability is a strength in marriage." },
    { id: 'a46', content: "Check in with each other daily. A simple 'how was your day?' matters." },
    { id: 'a47', content: "Build a strong support network together. Friends and family are important for your resilience." },
    { id: 'a48', content: "Learn to disagree respectfully. You won't always agree, and that's okay." },
    { id: 'a49', content: "Prioritize your mental health. A healthy mind makes for a healthier marriage." },
    { id: 'a50', content: "Tell each other 'I love you' every day. Never let them doubt it." },
    { id: 'a51', content: "Be curious about each other. Never stop asking questions." },
    { id: 'a52', content: "Value each other's opinions. Even if you differ, show respect for their perspective." },
    { id: 'a53', content: "Be supportive during tough times. That's when your partnership is tested most." },
    { id: 'a54', content: "Keep the playfulness alive. Don't take life too seriously all the time." },
    { id: 'a55', content: "Don't let small annoyances build up. Address them before they become big issues." },
    { id: 'a56', content: "Be mindfully present. When you're together, truly be there with your whole heart." },
    { id: 'a57', content: "Trust your intuition. If something feels off, talk about it." },
    { id: 'a58', content: "Understand each other's triggers. It helps you navigate sensitive topics with more care." },
    { id: 'a59', content: "Be grateful for each other. Focus on what's right in your relationship." },
    { id: 'a60', content: "Learn to co-regulate. Be the calm in each other's storm." },
    { id: 'a61', content: "Encourage each other's growth. Be the person who pushes them to be their best self." },
    { id: 'a62', content: "Be honest about your needs for alone time. It's not a rejection of your partner." },
    { id: 'a63', content: "Celebrate each other's successes as if they were your own." },
    { id: 'a64', content: "Practice forgiveness as a lifestyle, not just a one-time event." },
    { id: 'a65', content: "Remember that you're both on the same team. Always." },
    { id: 'a66', content: "Keep the spark alive with small gestures. A touch, a look, a kind word." },
    { id: 'a67', content: "Don't take each other for granted. Treat every day as a gift." },
    { id: 'a68', content: "Seek help if you need it. There's no shame in couples therapy." },
    { id: 'a69', content: "Be patient with the seasons of your marriage. Some are easier than others." },
    { id: 'a70', content: "Communicate your appreciation often. Everyone needs to feel valued." },
    { id: 'a71', content: "Always assume the best of your partner's intentions." },
    { id: 'a72', content: "Maintain your sense of wonder. Marriage is a continuous journey of discovery." },
    { id: 'a73', content: "Don't let the mundane tasks of life overshadow your connection." },
    { id: 'a74', content: "Be each other's safe haven. A place where you can be your true self." },
    { id: 'a75', content: "Keep your promises, especially the small ones." },
    { id: 'a76', content: "Don't let ego get in the way of a healthy relationship." },
    { id: 'a77', content: "Be willing to grow together. Change is inevitable; lean into it." },
    { id: 'a78', content: "Cherish the moments of quiet together. Sometimes silence is the best connection." },
    { id: 'a79', content: "Don't hold onto resentment. It's poison to a marriage." },
    { id: 'a80', content: "Focus on the positive traits of your partner." },
    { id: 'a81', content: "Take time for self-reflection. Understanding yourself helps you be a better partner." },
    { id: 'a82', content: "Be mindful of how you speak to each other. Words have power." },
    { id: 'a83', content: "Create a shared meaning for your life together." },
    { id: 'a84', content: "Nurture your physical connection. It's a key part of your bond." },
    { id: 'a85', content: "Don't stop being romantic. It keeps the relationship feeling fresh." },
    { id: 'a86', content: "Always look for ways to make your partner's life easier." },
    { id: 'a87', content: "Be transparent about your feelings, even the difficult ones." },
    { id: 'a88', content: "Commit to the long game. Marriage is a marathon, not a sprint." },
    { id: 'a89', content: "Find joy in the everyday moments. It's what life is made of." },
    { id: 'a90', content: "Keep your relationship a priority, no matter how busy life gets." },
    { id: 'a91', content: "Forgive yourself too. You're not going to be a perfect partner all the time." },
    { id: 'a92', content: "Listen with your heart, not just your ears." },
    { id: 'a93', content: "Be adventurous together. Try new things and go to new places." },
    { id: 'a94', content: "Create a culture of appreciation in your home." },
    { id: 'a95', content: "Value each other's time. Be punctual and respectful of their schedule." },
    { id: 'a96', content: "Stay curious about your partner's inner world." },
    { id: 'a97', content: "Celebrate your anniversary every year, no matter how long it's been." },
    { id: 'a98', content: "Remember why you fell in love in the first place." },
    { id: 'a99', content: "Be the person you want your partner to be." },
    { id: 'a100', content: "Love deeply, forgive quickly, and never stop growing together." }
  ],
  tips: [
    { id: 't1', content: "Define your 'Big Three' priorities before spending a single dollar. Is it the food, the venue, or the photography?" },
    { id: 't2', content: "Always set aside a 10% contingency fund for unexpected costs. They will happen." },
    { id: 't3', content: "Guest lists are the biggest budget driver. Every person you invite adds to the venue, food, drinks, and stationery costs." },
    { id: 't4', content: "Read every contract twice. Pay close attention to cancellation policies and 'hidden' service fees." },
    { id: 't5', content: "Work backwards from your wedding date to create a realistic planning timeline." },
    { id: 't6', content: "Don't feel pressured to follow every tradition. If it doesn't represent you, skip it." },
    { id: 't7', content: "Consider an 'off-peak' season or day of the week to save significantly on venue fees." },
    { id: 't8', content: "Hire a wedding coordinator for the day-of. It's the best investment for your peace of mind." },
    { id: 't9', content: "Communication with vendors is key. Get everything in writing to avoid misunderstandings." },
    { id: 't10', content: "Remember that at the end of the day, the most important thing is the marriage, not the party." },
    { id: 't11', content: "Start your guest list early. It will likely take much longer than you anticipate." },
    { id: 't12', content: "Be realistic about your DIY projects. Sometimes, hiring a pro is cheaper than buying all the supplies and your time." },
    { id: 't13', content: "Book your high-priority vendors (venue, photographer, caterer) at least 12-18 months in advance." },
    { id: 't14', content: "Don't forget to budget for the small things: tips, marriage license, beauty treatments, and day-of meals." },
    { id: 't15', content: "Create a separate email address just for wedding planning to keep your personal inbox clean." },
    { id: 't16', content: "Try on dresses early. Popular styles can have long lead times for ordering." },
    { id: 't17', content: "Have a 'Plan B' for outdoor weddings. Weather is the one thing you can't control." },
    { id: 't18', content: "Limit your Pinterest time. Use it for inspiration, but don't let it overwhelm you with unrealistic expectations." },
    { id: 't19', content: "Research the typical costs of weddings in your specific area. Prices vary wildly by location." },
    { id: 't20', content: "Be clear about who is paying for what. Have open, honest conversations with your family about financial contributions." },
    { id: 't21', content: "Select your bridal party with care. Choose people who will truly support and help you through the process." },
    { id: 't22', content: "Don't neglect your self-care during the planning process. Stress can take a toll on your health and relationships." },
    { id: 't23', content: "Invest in good photography. These are the memories you'll have forever." },
    { id: 't24', content: "Think about the guest experience. Consider transportation, lodging, and dietary needs." },
    { id: 't25', content: "Review your guest list one final time before sending out save-the-dates." },
    { id: 't26', content: "Consider a smaller wedding if your budget is tight. Quality over quantity often leads to a more memorable event." },
    { id: 't27', content: "Be open to alternative venues. Parks, libraries, and private estates can be unique and budget-friendly." },
    { id: 't28', content: "Negotiate where possible, but be respectful of vendor expertise and pricing." },
    { id: 't29', content: "Don't forget to plan your honeymoon too! It's your reward for all the planning." },
    { id: 't30', content: "Keep a detailed spreadsheet of all your expenses. Track every penny to stay on budget." },
    { id: 't31', content: "Schedule regular 'wedding-free' dates with your partner to talk about anything but the wedding." },
    { id: 't32', content: "Think about the lighting. It can completely transform the atmosphere of your venue." },
    { id: 't33', content: "Choose flowers that are in season. They'll be fresher and more affordable." },
    { id: 't34', content: "Be mindful of your guest's time. Keep the ceremony and speeches to a reasonable length." },
    { id: 't35', content: "Don't let social media pressure dictate your choices. Your wedding should be about you." },
    { id: 't36', content: "Have a central place for all your vendor contacts and notes." },
    { id: 't37', content: "Review your seating chart carefully. Consider guest relationships and comfort." },
    { id: 't38', content: "Don't forget to eat on your wedding day! Have a designated person to bring you snacks and water." },
    { id: 't39', content: "Remember to take some time alone with your new spouse right after the ceremony." },
    { id: 't40', content: "Trust your vendors. You hired them for their expertise, so let them do their jobs." },
    { id: 't41', content: "Consider the logistics of your venue. Is there enough parking? Are the restrooms easily accessible?" },
    { id: 't42', content: "Plan for a 'day-after' brunch if you have many out-of-town guests." },
    { id: 't43', content: "Don't be afraid to say 'no'. You can't please everyone, and it's your day." },
    { id: 't44', content: "Keep your invitation design clear and easy to read. Include all essential information." },
    { id: 't45', content: "Have an 'emergency kit' for the day of. Include safety pins, stain remover, aspirin, and mints." },
    { id: 't46', content: "Set a deadline for final RSVPs at least 2-3 weeks before the wedding." },
    { id: 't47', content: "Don't forget the importance of a good sound system. Your guests need to hear the ceremony and speeches." },
    { id: 't48', content: "Be intentional about your music choices. It sets the tone for the entire event." },
    { id: 't49', content: "If you're having a destination wedding, provide your guests with plenty of helpful information early on." },
    { id: 't50', content: "Remember that perfection is an illusion. Embrace the small imperfections; they make for great stories later." },
    { id: 't51', content: "Factor in the cost of dress alterations. They can be quite expensive." },
    { id: 't52', content: "Check the local laws for getting your marriage license well in advance." },
    { id: 't53', content: "If you're self-catering, be realistic about the amount of work involved and food safety." },
    { id: 't54', content: "Consider a first look. It can help calm your nerves and allow for more time with guests later." },
    { id: 't55', content: "Be mindful of the flow of your event. Avoid long gaps between the ceremony and reception." },
    { id: 't56', content: "Don't forget to thank your vendors and give them positive reviews after the wedding." },
    { id: 't57', content: "Keep your wedding party attire choices realistic for their budgets too." },
    { id: 't58', content: "Think about the sustainability of your choices. Consider eco-friendly options where possible." },
    { id: 't59', content: "Take plenty of photos during the planning process. They're part of the memory too." },
    { id: 't60', content: "Don't obsess over the small details. Most guests won't even notice them." },
    { id: 't61', content: "Research the history of your venue. It can add an extra layer of meaning to your day." },
    { id: 't62', content: "Have a plan for what happens with the flowers and decor after the wedding." },
    { id: 't63', content: "Be clear about your photography 'must-have' shot list." },
    { id: 't64', content: "Consider the accessibility needs of all your guests." },
    { id: 't65', content: "Don't forget to celebrate your bachelor/bachelorette parties with those you love." },
    { id: 't66', content: "Budget for your wedding rings. They're often an afterthought but a lifelong symbol." },
    { id: 't67', content: "Think about how you'll preserve your wedding dress and memories." },
    { id: 't68', content: "Don't let family drama overshadow your happiness. Focus on your partner." },
    { id: 't69', content: "Trust your gut feeling when choosing vendors. Chemistry matters." },
    { id: 't70', content: "Make sure you have a clear plan for the rehearsal and dinner." },
    { id: 't71', content: "Budget for favors if you feel they're necessary, but remember they're optional." },
    { id: 't72', content: "Don't forget the importance of a good hair and makeup trial." },
    { id: 't73', content: "Think about the transportation for the bridal party on the day-of." },
    { id: 't74', content: "Have a designated person to handle any vendor questions or issues on the wedding day." },
    { id: 't75', content: "Create a detailed timeline for the day of and share it with everyone involved." },
    { id: 't76', content: "Don't forget to include travel time between locations in your timeline." },
    { id: 't77', content: "Be mindful of the time of day you're getting married. It affects lighting and temperature." },
    { id: 't78', content: "Research the best time to buy certain items. Sales happen throughout the year." },
    { id: 't79', content: "Think about how you'll handle any leftover food or drinks." },
    { id: 't80', content: "Don't forget to take a few deep breaths and soak it all in throughout the day." },
    { id: 't81', content: "Review your wedding website regularly to ensure all information is up to date." },
    { id: 't82', content: "Consider a videographer. Sometimes seeing the day in motion is just as important as photos." },
    { id: 't83', content: "Don't let the planning consume your every waking moment. Take breaks." },
    { id: 't84', content: "Be clear about your dietary restrictions with your caterer." },
    { id: 't85', content: "Think about the children. If you're inviting them, plan for some entertainment." },
    { id: 't86', content: "Budget for your wedding insurance. It provides peace of mind in case of unforeseen events." },
    { id: 't87', content: "Have a plan for where you'll get ready on the morning of." },
    { id: 't88', content: "Don't forget to pack your 'go bag' for the honeymoon in advance." },
    { id: 't89', content: "Be intentional about the people you choose to have by your side during the ceremony." },
    { id: 't90', content: "Remember that the focus is on your love story, not just the event." },
    { id: 't91', content: "Factor in the cost of vendor meals. It's a standard courtesy." },
    { id: 't92', content: "Check the acoustics of your venue. Some spaces can be very echoey." },
    { id: 't93', content: "Think about how you'll handle any gifts you receive." },
    { id: 't94', content: "Don't forget to write your own vows if that's something you want to do." },
    { id: 't95', content: "Celebrate the engagement phase. It's a special time in itself." },
    { id: 't96', content: "Be realistic about what you can achieve in the final week before the wedding." },
    { id: 't97', content: "Think about the transition from the ceremony to the reception for your guests." },
    { id: 't98', content: "Don't let the weight of expectations make you lose sight of the joy." },
    { id: 't99', content: "Nurture your relationship throughout the entire process." },
    { id: 't100', content: "Enjoy the journey. It's a once-in-a-lifetime experience!" }
  ]
};
